/**
 * Intrinsic pixel width of every `-lg` image, by public path.
 *
 * GENERATED by `scripts/generate-image-widths.mjs` — do not edit by hand.
 * Run `npm run images:widths` after changing anything under `public/images`.
 *
 * The large tier has no single width: assets over 400 KB are capped at 2000px
 * by `shrink-oversized-avif.mjs`, the rest stay at 2400px. Emitting a single
 * hardcoded descriptor mis-declared 13 of 19 files. A plain data map keeps this
 * module filesystem-free, so it stays safe to import from client components.
 */
export const LARGE_TIER_WIDTHS: Readonly<Record<string, number>> = {
  '/images/hero/hero-404-lg.avif': 2000,
  '/images/hero/hero-homepage-lg.avif': 2400,
  '/images/journal/library/journal-3-library-hero-lg.avif': 2000,
  '/images/journal/light/journal-2-light-hero-lg.avif': 2400,
  '/images/journal/stone/journal-1-stone-hero-lg.avif': 2000,
  '/images/projects/amagansett-house/amagansett-hero-lg.avif': 2400,
  '/images/projects/amagansett-house/amagansett-lawn-lg.avif': 2000,
  '/images/projects/baxter-street-residence/baxter-evening-lg.avif': 2400,
  '/images/projects/baxter-street-residence/baxter-stair-lg.avif': 2400,
  '/images/projects/hudson-house/hudson-house-living-lg.avif': 2000,
  '/images/projects/hudson-house/hudson-house-orchard-lg.avif': 2000,
  '/images/projects/mercer-street-loft/mercer-loft-ceiling-lg.avif': 2400,
  '/images/projects/mercer-street-loft/mercer-loft-evening-lg.avif': 2400,
  '/images/projects/mercer-street-loft/mercer-loft-hero-lg.avif': 2400,
  '/images/projects/park-avenue-residence/park-avenue-dining-lg.avif': 2400,
  '/images/projects/park-avenue-residence/park-avenue-evening-lg.avif': 2400,
  '/images/projects/tribeca-penthouse/penthouse-living-lg.avif': 2400,
  '/images/projects/tribeca-penthouse/penthouse-view-lg.avif': 2000,
  '/images/projects/west-11th-townhouse/west-11th-facade-lg.avif': 2400,
  '/images/projects/west-11th-townhouse/west-11th-garden-room-lg.avif': 2400,
  '/images/projects/wythe-residence/wythe-evening-lg.avif': 2400,
  '/images/projects/wythe-residence/wythe-hero-lg.avif': 2400,
  '/images/projects/wythe-residence/wythe-open-room-lg.avif': 2400,
}
